language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pytest>=5.4.2 coveralls>=2.0.0 pytest-cov>=2.9.0
  - pip install flake8>=3.8.2 flake8-bugbear>=20.1.4 pep8-naming>=0.10.0
  - pip install black>=19.10b0
script:
  - pytest -v --ignore=setup.py --cov=flake8parser
  - black --check .
  - flake8
after_success:
  - coveralls
