language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run black --check .
  - poetry run flake8
  - poetry run pytest -vvv --cov=flake8parser tests/
after_success:
  - poetry run coveralls
